<?php

namespace SIV\MainBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * MessagesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MessagesRepository extends EntityRepository
{
    public function inbox($user){

        $queryBuilder = $this
            ->createQueryBuilder('m')
            ->join('m.sender', 's')
            ->join('m.recever', 'r')
            ->addSelect('s')
            ->addSelect('r')
            ->where('r.id = :user')
            ->orderBy('m.createdAt', 'desc')
            ->setParameters([
                'user' => $user
            ]);
        // On récupère la Query à partir du QueryBuilder
        $query = $queryBuilder->getQuery();
        // On récupère les résultats à partir de la Query
        $results = $query->getResult();
        //$results = $results;


        // var_dump($results); exit;
        return $results;
    }
}
