<?php

namespace SIV\MainBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * VisitesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VisitesRepository extends EntityRepository
{
    public function getPresent(){

        $queryBuilder = $this
            ->createQueryBuilder('v')
            ->where('v.dateSortie = :ds')
            ->andWhere('v.heureSortie = :hs')
            ->setParameters([
                'ds' => "null",
                'hs' => "null"
            ]);
        // On récupère la Query à partir du QueryBuilder
        $query = $queryBuilder->getQuery();
        // On récupère les résultats à partir de la Query
        $results = $query->getResult();
        //$results = $results;


        // var_dump($results); exit;
        return $results;


    }
}
